### PR TITLE
Remove display property from sizeFull

### PR DESCRIPTION
**Pull request by simonsmith**
Addresses #35

### CODE REVIEW

**Comment by giuseppeg** [comment]
Does it make sense to remove `box-sizing` too? Either ways it looks good to me 🚢

**Comment by simonsmith** [comment]
> Does it make sense to remove box-sizing too?

Good question. I did, and the test failed (the element moved outside its parent). I wondered if the utility should make an assumption that the page it lives in has already set `border-box`. Maybe these days we can assume so?

**Comment by giuseppeg** [comment]
In my opinion utilities shouldn't make assumptions.
They should do a single thing (in this case set width to 100%) and have no "side-effects".
If one needs `box-sizing` he/she can use another utility class or set it globally.

**Comment by simonsmith** [comment]
Well I guess if we take the `box-sizing` away, we are assuming that the user handles it. I think that's cool though, and more inline with the doing one thing as you say.

Plus `suitcss-base` already sets it.

**Comment by timkelty** [comment]
Agreed on all accounts!

**Pull request merged**
